CREATE TABLE ESQUEMA.MI_TABLA (
   MT_CLAVE           NUMBER(3)    NOT NULL,
   MT_DESCRIPCION     VARCHAR2(50) NULL      
)  TABLESPACE TBS_ESQUEMA_DATA;

ALTER TABLE ESQUEMA.MI_TABLA
   ADD CONSTRAINT PK_MI_TABLA
   PRIMARY KEY (MT_CLAVE) 
   USING INDEX TABLESPACE TBS_ESQUEMA_IDX;
