SELECT DISTINCT name, type FROM USER_SOURCE WHERE TYPE IN ('PROCEDURE','FUNCTION')
ORDER BY 2;

SELECT DISTINCT name, type 
FROM ALL_SOURCE 
WHERE OWNER = USER AND TYPE IN ('PROCEDURE','FUNCTION')
ORDER BY 2;

SELECT DISTINCT name, type 
FROM ALL_SOURCE 
WHERE TYPE IN ('PROCEDURE','FUNCTION')
ORDER BY 2;
